#!/usr/bin/bash
if [ -z "${SERVER_NAME}" ]; then
    echo 'Error: SERVER_NAME is empty or not set'
    exit 1
fi
if [ -z "${WWW_USER}" ]; then
    echo 'Error: WWW_USER is empty or not set'
    exit 1
fi

if [ ! -d "/etc/lighttpd/certs/$SERVER_NAME" ]; then
    echo "Issue self-signed certficate"
    cd /etc/lighttpd/certs
    ./selfsigned
fi

domains_txt=/usr/local/etc/dehydrated/domains.txt
if [ ! -s "$domains_txt" ]; then
    echo "Create domains.txt:"
    echo "$SERVER_NAME www.${SERVER_NAME}"
    echo "$SERVER_NAME www.${SERVER_NAME}" > $domains_txt
fi

if [ ! -d "/usr/local/etc/dehydrated/accounts" ]; then
    echo "Register CA account"
    chown -R ${WWW_USER}:${WWW_USER} /usr/local/etc/dehydrated
    su -s /usr/bin/bash $WWW_USER -c "dehydrated --register --accept-terms"
fi

if [ ! -d "/var/log/lighttpd" ]; then
    mkdir /var/log/lighttpd
    touch /var/log/lighttpd/access.log
    chown -R ${WWW_USER}:${WWW_USER} /var/log/lighttpd
fi
