services:
  lighttpd:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
        - LIGHTTPD_VERSION=${LIGHTTPD_VERSION}
        - LIGHTTPD_SHA256=${LIGHTTPD_SHA256}
      labels:
        - "org.opencontainers.image.description=Unprivileged Lighttpd image on top of PHP-FPM (debian based)"
        - "org.opencontainers.image.vendor=Dmitriy Kosolapov"
        - "org.opencontainers.image.source=https://github.com/dmkos/php-containers"
        - "org.opencontainers.image.licenses=MIT"
      tags:
        - "docker.io/dmkos/php:${PHP_VERSION}-lighttpd-${LIGHTTPD_VERSION}-trixie"
        - "docker.io/dmkos/php:${PHP_VERSION}-lighttpd-1.4-trixie"
        - "docker.io/dmkos/php:${PHP_VERSION}-lighttpd-trixie"
        - "docker.io/dmkos/php:8.4-lighttpd-1.4-trixie"
        - "docker.io/dmkos/php:8.4-lighttpd-trixie"
        - "docker.io/dmkos/php:8-lighttpd-trixie"
        - "docker.io/dmkos/php:lighttpd-trixie"
        - "docker.io/dmkos/php:${PHP_VERSION}-lighttpd"
        - "docker.io/dmkos/php:8.4-lighttpd-1.4"
        - "docker.io/dmkos/php:8.4-lighttpd"
        - "docker.io/dmkos/php:8-lighttpd"
        - "docker.io/dmkos/php:lighttpd"
        - "ghcr.io/dmkos/php:${PHP_VERSION}-lighttpd-${LIGHTTPD_VERSION}-trixie"
        - "ghcr.io/dmkos/php:${PHP_VERSION}-lighttpd-1.4-trixie"
        - "ghcr.io/dmkos/php:${PHP_VERSION}-lighttpd-trixie"
        - "ghcr.io/dmkos/php:8.4-lighttpd-1.4-trixie"
        - "ghcr.io/dmkos/php:8.4-lighttpd-trixie"
        - "ghcr.io/dmkos/php:8-lighttpd-trixie"
        - "ghcr.io/dmkos/php:lighttpd-trixie"
        - "ghcr.io/dmkos/php:${PHP_VERSION}-lighttpd"
        - "ghcr.io/dmkos/php:8.4-lighttpd-1.4"
        - "ghcr.io/dmkos/php:8.4-lighttpd"
        - "ghcr.io/dmkos/php:8-lighttpd"
        - "ghcr.io/dmkos/php:lighttpd"
    environment:
      LIGHTTPD_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - "8000:9000"
      - "8443:9443"
    volumes:
      - ./demo/app:/var/www/html
      - ./demo/certs:/etc/lighttpd/certs
      - ./demo/config:/usr/local/etc/lighttpd/conf.d
  lighttpd-s6:
    build:
      context: .
      dockerfile: s6.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - LIGHTTPD_VERSION=${LIGHTTPD_VERSION}
        - S6_OVERLAY_VERSION=${S6_OVERLAY_VERSION}
      labels:
        - "org.opencontainers.image.description=s6-overlay Lighttpd image on top of PHP-FPM (debian based)"
        - "org.opencontainers.image.vendor=Dmitriy Kosolapov"
        - "org.opencontainers.image.source=https://github.com/dmkos/php-containers"
        - "org.opencontainers.image.licenses=MIT"
      tags:
        - "docker.io/dmkos/php:${PHP_VERSION}-lighttpd-${LIGHTTPD_VERSION}-s6-trixie"
        - "docker.io/dmkos/php:${PHP_VERSION}-lighttpd-1.4-s6-trixie"
        - "docker.io/dmkos/php:${PHP_VERSION}-lighttpd-s6-trixie"
        - "docker.io/dmkos/php:8.4-lighttpd-1.4-s6-trixie"
        - "docker.io/dmkos/php:8.4-lighttpd-s6-trixie"
        - "docker.io/dmkos/php:8-lighttpd-s6-trixie"
        - "docker.io/dmkos/php:lighttpd-s6-trixie"
        - "docker.io/dmkos/php:${PHP_VERSION}-lighttpd-s6"
        - "docker.io/dmkos/php:8.4-lighttpd-1.4-s6"
        - "docker.io/dmkos/php:8.4-lighttpd-s6"
        - "docker.io/dmkos/php:8-lighttpd-s6"
        - "docker.io/dmkos/php:lighttpd-s6"
        - "ghcr.io/dmkos/php:${PHP_VERSION}-lighttpd-${LIGHTTPD_VERSION}-s6-trixie"
        - "ghcr.io/dmkos/php:${PHP_VERSION}-lighttpd-1.4-s6-trixie"
        - "ghcr.io/dmkos/php:${PHP_VERSION}-lighttpd-s6-trixie"
        - "ghcr.io/dmkos/php:8.4-lighttpd-1.4-s6-trixie"
        - "ghcr.io/dmkos/php:8.4-lighttpd-s6-trixie"
        - "ghcr.io/dmkos/php:8-lighttpd-s6-trixie"
        - "ghcr.io/dmkos/php:lighttpd-s6-trixie"
        - "ghcr.io/dmkos/php:${PHP_VERSION}-lighttpd-s6"
        - "ghcr.io/dmkos/php:8.4-lighttpd-1.4-s6"
        - "ghcr.io/dmkos/php:8.4-lighttpd-s6"
        - "ghcr.io/dmkos/php:8-lighttpd-s6"
        - "ghcr.io/dmkos/php:lighttpd-s6"
    environment:
      LIGHTTPD_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - "8006:9000"
      - "6443:9443"
    volumes:
      - ./demo/app:/var/www/html
      - ./demo/certs:/etc/lighttpd/certs
      - ./demo/config:/usr/local/etc/lighttpd/conf.d
