ARG FREEBSD=14.3
FROM docker.io/freebsd/freebsd-runtime:$FREEBSD

# Install software
ARG PHP=php84
RUN set -eux; \
        pkg bootstrap -y; \
        # use the latest packages
        mkdir -p /usr/local/etc/pkg/repos; \
        echo 'FreeBSD: { url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf; \
        pkg install -y \
            ${PHP} \
            ${PHP}-ctype \
            ${PHP}-curl \
            ${PHP}-dom \
            ${PHP}-fileinfo \
            ${PHP}-filter \
            ${PHP}-iconv \
            ${PHP}-mbstring \
            ${PHP}-opcache \
            ${PHP}-pdo_sqlite \
            ${PHP}-phar \
            ${PHP}-posix \
            ${PHP}-readline \
            ${PHP}-session \
            ${PHP}-simplexml \
            ${PHP}-sodium \
            ${PHP}-sqlite3 \
            ${PHP}-tokenizer \
            ${PHP}-xml \
            ${PHP}-xmlreader \
            ${PHP}-xmlwriter \
            ${PHP}-zlib; \
        # cleanup to reduce image size
        pkg clean -ay; \
        rm -rf /var/db/pkg/repos

# Application directory
RUN set -eux; \
        [ ! -d /usr/local/www/html ]; \
        mkdir -p /usr/local/www/html; \
        chmod 755 /usr/local/www; \
        chmod 1777 /usr/local/www/html
COPY --chmod=644 --chown=80:80 html/index.php /usr/local/www/html/

# Configure
ENV PHP_INI_DIR /usr/local/etc
COPY etc/php-fpm.d/* ${PHP_INI_DIR}/php-fpm.d/
COPY etc/php/* ${PHP_INI_DIR}/php/

RUN chmod 755 /usr/local/sbin
COPY --chmod=755 podman-php-entrypoint /usr/local/sbin/
ENTRYPOINT ["podman-php-entrypoint"]
WORKDIR /usr/local/www/html

# Override stop signal to stop process gracefully
STOPSIGNAL SIGQUIT

EXPOSE 9000
CMD ["php-fpm"]
